(in-package #:end-wolf)

(deftype dtcd () '(unsigned-byte 8))
(defconstant +dtcd-inf+ (1- (ash 1 8)))
(deftype dtcdbase () `(simple-array dtcd (*)))

(defvar *dtcds* (make-array 19 :initial-contents (iter (repeat 19) (collect (cons nil nil)))))

(defmacro wolf-dtcd-updater (dtcd-var sheep-dtcd sheep-dtm n-piece)
  `(lambda (next-sm next-wm)
     (let ((addr (encode-mask next-sm next-wm ,n-piece)))
       (when (zerop (aref ,sheep-dtm addr))
         (setq ,dtcd-var (min ,dtcd-var (1+ (aref ,sheep-dtcd addr))))))))

(defmacro sheep-dtcd-updater (dtcd-var wolf-dtcd wolf-dtm n-piece)
  `(lambda (next-sm next-wm)
     (let ((addr (encode-mask next-sm next-wm ,n-piece)))
       (when (zerop (aref ,wolf-dtm addr))
         (setq ,dtcd-var (max ,dtcd-var (aref ,wolf-dtcd addr)))))))

(defun wolf-dtcd-forward-scan
    (sheep-dtm wolf-dtm sheep-dtcd wolf-dtcd prev-sheep-dtm n-piece)
  (declare (tablebase sheep-dtm wolf-dtm prev-sheep-dtm)
           (dtcdbase sheep-dtcd wolf-dtcd))
  (sb-thread:barrier (:memory))
  (assert (= (length sheep-dtm) (length wolf-dtm) (length sheep-dtcd) (length wolf-dtcd)
             (max-state n-piece)))
  (assert (= (length prev-sheep-dtm) (max-state (1- n-piece))))
  (format t "~&Scan, ~a pieces wolf-to-move.~%" n-piece)
  (do-states (state sm wm n-piece) ()
    (when (zerop (aref wolf-dtm state))
      (let ((dtcd +dtcd-inf+))
        (declare (dtcd dtcd))
        (wolf-forward sm wm
                      (wolf-dtcd-updater dtcd sheep-dtcd sheep-dtm n-piece)
                      (lambda (next-sm next-wm)
                        (when (zerop (aref prev-sheep-dtm
                                           (encode-mask next-sm next-wm (1- n-piece))))
                          (setq dtcd 0))))
        (setf (aref wolf-dtcd state) dtcd)))))

(defun sheep-dtcd-forward-scan (sheep-dtm wolf-dtm sheep-dtcd wolf-dtcd n-piece)
  (declare (tablebase sheep-dtm wolf-dtm)
           (dtcdbase sheep-dtcd wolf-dtcd))
  (sb-thread:barrier (:memory))
  (assert (= (length sheep-dtm) (length wolf-dtm) (length sheep-dtcd) (length wolf-dtcd)
             (max-state n-piece)))
  (format t "~&Scan, ~a pieces sheep-to-move.~%" n-piece)
  (let ((results
          (do-states (state sm wm n-piece) ((delta 0))
            (declare (fixnum delta))
            (when (zerop (aref sheep-dtm state))
              (let ((old-dtcd (aref sheep-dtcd state))
                    (dtcd 0))
                (declare (dtcd dtcd))
                (sheep-forward sm wm (sheep-dtcd-updater dtcd wolf-dtcd wolf-dtm n-piece))
                (unless (= dtcd old-dtcd)
                  (incf delta)
                  (setf (aref sheep-dtcd state) dtcd)))))))
    (reduce #'+ results :key #'car)))

(defmacro dtcd-work-pusher (worklist-var dtm n-piece)
  `(lambda (prev-sm prev-wm)
     (when (zerop (aref ,dtm (encode-mask prev-sm prev-wm ,n-piece)))
       (push (logior (ash prev-sm 25) prev-wm) ,worklist-var))))

(defun wolf-dtcd-forward-scan-create-worklist
    (sheep-dtm wolf-dtm sheep-dtcd wolf-dtcd prev-sheep-dtm n-piece)
  (declare (tablebase sheep-dtm wolf-dtm prev-sheep-dtm prev-sheep-dtm)
           (dtcdbase sheep-dtcd wolf-dtcd))
  (sb-thread:barrier (:memory))
  (format t "~&Scan create worklist, ~a pieces wolf-to-move.~%" n-piece)
  (let ((results
          (do-states (state sm wm n-piece) ((worklist))
            (when (zerop (aref wolf-dtm state))
              (let ((old-dtcd (aref wolf-dtcd state))
                    (dtcd +dtcd-inf+))
                (declare (dtcd dtcd))
                (wolf-forward sm wm
                              (wolf-dtcd-updater dtcd sheep-dtcd sheep-dtm n-piece)
                              (lambda (next-sm next-wm)
                                (when (zerop (aref prev-sheep-dtm
                                                   (encode-mask next-sm next-wm (1- n-piece))))
                                  (setq dtcd 0))))
                (unless (= old-dtcd dtcd)
                  (sheep-backward sm wm (dtcd-work-pusher worklist sheep-dtm n-piece))
                  (setf (aref wolf-dtcd state) dtcd)))))))
    (mapcan #'car results)))

(defun sheep-dtcd-forward-scan-use-worklist (wolf-dtm sheep-dtcd wolf-dtcd worklist n-piece)
  (declare (tablebase wolf-dtm)
           (dtcdbase sheep-dtcd wolf-dtcd))
  (sb-thread:barrier (:memory))
  (format t "~&Worklist, ~a pieces sheep-to-move.~%" n-piece)
  (let ((results
          (do-worklist (state sm wm worklist n-piece) ((worklist))
            (let ((old-dtcd (aref sheep-dtcd state))
                  (dtcd 0))
              (declare (dtcd dtcd))
              (sheep-forward sm wm (sheep-dtcd-updater dtcd wolf-dtcd wolf-dtm n-piece))
              (unless (= old-dtcd dtcd)
                (wolf-move-backward sm wm (dtcd-work-pusher worklist wolf-dtm n-piece))
                (setf (aref sheep-dtcd state) dtcd))))))
    (mapcan #'car results)))

(defun wolf-dtcd-forward-scan-use-worklist
    (sheep-dtm sheep-dtcd wolf-dtcd prev-sheep-dtm worklist n-piece)
  (declare (tablebase sheep-dtm prev-sheep-dtm)
           (dtcdbase sheep-dtcd wolf-dtcd))
  (sb-thread:barrier (:memory))
  (format t "~&Worklist, ~a pieces wolf-to-move.~%" n-piece)
  (let ((results
          (do-worklist (state sm wm worklist n-piece) ((worklist))
            (let ((old-dtcd (aref wolf-dtcd state))
                  (dtcd +dtcd-inf+))
              (declare (dtcd dtcd))
              (wolf-forward sm wm
                            (wolf-dtcd-updater dtcd sheep-dtcd sheep-dtm n-piece)
                            (lambda (next-sm next-wm)
                              (when (zerop (aref prev-sheep-dtm
                                                 (encode-mask next-sm next-wm (1- n-piece))))
                                (setq dtcd 0))))
              (unless (= old-dtcd dtcd)
                (sheep-backward sm wm (dtcd-work-pusher worklist sheep-dtm n-piece))
                (setf (aref wolf-dtcd state) dtcd))))))
    (mapcan #'car results)))

(defun init-dtcd (n-piece)
  (unless (car (aref *dtcds* n-piece))
    (format t "Allocating ~a pieces sheep-to-move table~%" n-piece)
    (setf (car (aref *dtcds* n-piece))
          (static-vectors:make-static-vector (max-state n-piece)
                                             :initial-element +dtcd-inf+
                                             :element-type 'dtcd)))
  (unless (cdr (aref *dtcds* n-piece))
    (format t "Allocating ~a pieces wolf-to-move table~%" n-piece)
    (setf (cdr (aref *dtcds* n-piece))
          (static-vectors:make-static-vector (max-state n-piece)
                                             :initial-element +dtcd-inf+
                                             :element-type 'dtcd))))

(defun summary-dtcd (n-piece &optional (to-move 's))
  (sb-thread:barrier (:memory))
  (format t "~&Computing summary.~%")
  (let* ((dtcdbase (or (ecase to-move
                         (s (car (aref *dtcds* n-piece)))
                         (w (cdr (aref *dtcds* n-piece))))
                       (progn
                         (format t "Table not loaded.~%")
                         (return-from summary-dtcd))))
         (tablebase (or (ecase to-move
                          (s (car (aref *endgames* n-piece)))
                          (w (cdr (aref *endgames* n-piece))))
                        (progn
                          (format t "DTM not loaded.~%")
                          (return-from summary-dtcd))))
         (results
           (do-states (state sm wm n-piece)
               ((total 0)
                (dtcd-inf 0)
                (dtcd-max 0))
             (declare (dtcdbase dtcdbase)
                      (tablebase tablebase)
                      (fixnum total dtcd-inf dtcd-max))
             (when (zerop (aref tablebase state))
               (incf total)
               (let ((dtcd (aref dtcdbase state)))
                 (if (< dtcd +dtcd-inf+)
                     (setq dtcd-max (max dtcd-max dtcd))
                     (incf dtcd-inf))))))
         (total (reduce #'+ results :key #'first))
         (dtcd-inf (reduce #'+ results :key #'second))
         (dtcd-max (reduce #'max results :key #'third)))
    (format t "~&total: ~a~%" total)
    (format t "infinity: ~a (~,2f%)~%" dtcd-inf (/ (* dtcd-inf 100) total))
    (format t "max: ~a" dtcd-max)))

(defun run-dtcd (n-piece)
  (assert (<= 8 n-piece 18))
  (unless (car (aref *endgames* (1- n-piece)))
    (error "~a pieces sheep-to-move table not available." (1- n-piece)))
  (unless (car (aref *endgames* n-piece))
    (error "~a pieces sheep-to-move table not available." n-piece))
  (unless (cdr (aref *endgames* n-piece))
    (error "~a pieces wolf-to-move table not available." n-piece))
  (init-dtcd n-piece)
  (iter (with sheep-dtm = (car (aref *endgames* n-piece)))
    (with wolf-dtm = (cdr (aref *endgames* n-piece)))
    (with prev-sheep-dtm = (car (aref *endgames* (1- n-piece))))
    (with sheep-dtcd = (car (aref *dtcds* n-piece)))
    (with wolf-dtcd = (cdr (aref *dtcds* n-piece)))
    (for n-iter from 1)
    (wolf-dtcd-forward-scan sheep-dtm wolf-dtm sheep-dtcd wolf-dtcd prev-sheep-dtm n-piece)
    (let ((delta (sheep-dtcd-forward-scan sheep-dtm wolf-dtm sheep-dtcd wolf-dtcd n-piece)))
      (summary-dtcd n-piece)
      (format t "~&state change: ~a~%" delta)
      (cond ((zerop delta)
             (format t "~&===Done===~%")
             (summary-dtcd n-piece)
             (return-from run-dtcd))
            ((and (>= n-iter *worklist-min-n-iter*)
                  (< delta (* *worklist-threshold* (max-state n-piece)))
                  (< delta *worklist-limit*))
             (format t "~&===Switch to worklist===~%")
             (run-dtcd-worklist n-piece)
             (return-from run-dtcd))))))

(defun run-dtcd-worklist (n-piece)
  (assert (<= 7 n-piece 18))
  (iter (with sheep-dtm = (car (aref *endgames* n-piece)))
    (with wolf-dtm = (cdr (aref *endgames* n-piece)))
    (with sheep-dtcd = (car (aref *dtcds* n-piece)))
    (with wolf-dtcd = (cdr (aref *dtcds* n-piece)))
    (with prev-sheep-dtm = (car (aref *endgames* (1- n-piece))))
    (with processed = 0)
    (for worklist
         initially (wolf-dtcd-forward-scan-create-worklist
                    sheep-dtm wolf-dtm sheep-dtcd wolf-dtcd prev-sheep-dtm n-piece)
         then (wolf-dtcd-forward-scan-use-worklist
               sheep-dtm sheep-dtcd wolf-dtcd prev-sheep-dtm worklist n-piece))
    (while worklist)
    (setq worklist (sheep-dtcd-forward-scan-use-worklist
                    wolf-dtm sheep-dtcd wolf-dtcd worklist n-piece))
    (let ((s (length worklist)))
      (format t "~&worklist size: ~a~%" s)
      (when (> (floor (+ s processed) 1000000)
               (floor processed 1000000))
        (summary-dtcd n-piece)))
    (while worklist))
  (format t "~&===Done===~%")
  (summary-dtcd n-piece))

(defun unload-dtcds (&optional (n-piece t))
  (flet ((unload (i)
           (let ((p (aref *dtcds* i)))
             (when (car p)
               (format t "Unloading ~a pieces sheep-to-move table~%" i)
               (static-vectors:free-static-vector (car p))
               (rplaca p nil))
             (when (cdr p)
               (format t "Unloading ~a pieces wolf-to-move table~%" i)
               (static-vectors:free-static-vector (cdr p))
               (rplacd p nil))
             nil)))
    (if (eq n-piece t)
        (iter (for i from 0 below (length *dtcds*))
          (unload i))
        (unload n-piece))))

(defun run-dtcd-all (directory-path &key (from 8) (to 18))
  (setq directory-path (uiop:ensure-directory-pathname directory-path))
  (flet ((le (n)
           (load-endgames n
                 (make-pathname :name (format nil "wolf-dtm-~as" n)
                                :type "bin" :defaults directory-path)
                 (make-pathname :name (format nil "wolf-dtm-~aw" n)
                                :type "bin" :defaults directory-path))))
    (le (1- from))
    (iter (for n-piece from from to to)
      (le n-piece)
      (run-dtcd n-piece)
      (save-dtcds n-piece
                  (make-pathname :name (format nil "wolf-dtcd-~as" n-piece)
                                 :type "bin" :defaults directory-path)
                  (make-pathname :name (format nil "wolf-dtcd-~aw" n-piece)
                                 :type "bin" :defaults directory-path))
      (unload-dtcds n-piece)
      (unload-endgames (1- n-piece))))
  (unload-dtcds)
  (unload-endgames))

(defun load-dtcds (n-piece sheep-file wolf-file)
  (format t "Reading ~a pieces sheep-to-move from ~a.~%" n-piece sheep-file)
  (unless (car (aref *dtcds* n-piece))
    (setf (car (aref *dtcds* n-piece))
          (static-vectors:make-static-vector (max-state n-piece) :element-type 'dtcd)))
  (with-open-file (in sheep-file :element-type 'dtcd)
    (read-sequence (car (aref *dtcds* n-piece)) in))
  (format t "Reading ~a pieces wolf-to-move from ~a.~%" n-piece wolf-file)
  (unless (cdr (aref *dtcds* n-piece))
    (setf (cdr (aref *dtcds* n-piece))
          (static-vectors:make-static-vector (max-state n-piece) :element-type 'dtcd)))
  (with-open-file (in wolf-file :element-type 'fate)
    (read-sequence (cdr (aref *dtcds* n-piece)) in))
  t)

(defun save-dtcds (n-piece sheep-file wolf-file)
  (format t "Writing ~a pieces sheep-to-move from ~a.~%" n-piece sheep-file)
  (with-open-file (out sheep-file :direction :output :element-type 'dtcd)
    (write-sequence (car (aref *dtcds* n-piece)) out))
  (format t "Writing ~a pieces wolf-to-move from ~a.~%" n-piece wolf-file)
  (with-open-file (out wolf-file :direction :output :element-type 'dtcd)
    (write-sequence (cdr (aref *dtcds* n-piece)) out))
  t)
